<?xml version="1.0" encoding="UTF-8"?>
    <!ELEMENT rss (channel)>
    <!ATTLIST rss version (0.91 | 1.0 | 2.0) #REQUIRED>

    <!ELEMENT channel (title, link, description, language?, image?, item+)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT link (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT language (#PCDATA)>

    <!ELEMENT image (title, url, link, width?, height?)>
    <!ELEMENT url (#PCDATA)>
    <!ELEMENT width (#PCDATA)>
    <!ELEMENT height (#PCDATA)>

    <!ELEMENT item (title, link, description)>
